import axios from "axios";
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Header from "../../components/Header/Header";
import CardWrapper from '../../components/Card-wrapper/Card-wrapper';
import Spinner from '../../components/Spinner/Spinner'
import Banner from "../../components/Banner/Banner";

export default function Home() {
  const [characters, setCharacters] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await axios.get(
          "https://hp-api.onrender.com/api/characters"
        );
        setCharacters(response.data);
      } catch (error) {
        console.error("Error fetching data:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  const handleDelete = (characterId) => {
    console.log(characterId)
  
    setCharacters((prevCharacters) => prevCharacters.filter((character) => character.id !== characterId));
  };

  return (
    <>
      <Head>
        <title>Harry Potter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Banner />
        {loading ? (
          <Spinner />
        ) : (
          <CardWrapper characters={characters} onDelete={handleDelete} />
        )}
        <div style={{flex: '1 1 30%',  padding: '20px'}}></div>
      </main>
    </>
  );
}
